import { ProfileCard, ProfileIcon, ProfileFrame, ProfileHeading } from "@/components/profile/profile-ui";
import { previewIdentity } from "@/lib/profile/preview-profile";

const faqs = [
  { question: "What amount should I enter?", answer: "Choose the document type first, then enter the amount named by the calculator field. Review the fee breakdown before creating an invoice." },
  { question: "Why is a mortgage cheaper than an assignment of the same value?", answer: "The calculator applies the schedule for the document type you select. Check the selected type and its breakdown if a result seems unexpected." },
  { question: "What fee applies to an Irrevocable Power of Attorney?", answer: "Select the Power of Attorney document type and answer the underlying-transaction question. The calculator shows the resulting basis and fee." },
  { question: "Is the calculated fee the amount I must charge?", answer: "Review the calculator's terms and the applicable legal requirements before agreeing a fee with your client." },
  { question: "Why have I not received a Certificate of Compliance?", answer: "A certificate appears only after the branch completes payment verification and issues one. Ask your branch about a specific pending or rejected transaction." },
  { question: "I registered without a branch code. Can I add one?", answer: "Contact your branch administrator about affiliation changes. This preview cannot change a registered branch." },
  { question: "Do I lose my certificates if my subscription lapses?", answer: "Existing issued certificates are separate records. Ask your branch for help with access or a specific certificate." },
];

export function ProfileHelp() {
  return <ProfileFrame><ProfileHeading description="Answers to common questions, and how to reach your branch." title="Help & Support"/><div className="mx-auto max-w-[760px] space-y-4"><ProfileCard icon={<ProfileIcon kind="book"/>} title="Frequently asked"><div className="divide-y divide-[#eceeee]">{faqs.map((faq) => <details className="group py-4 first:pt-1 last:pb-1" key={faq.question}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-[16px] font-semibold marker:hidden"><span>{faq.question}</span><span aria-hidden="true" className="text-[22px] text-[#66717e] transition-transform group-open:rotate-180">⌄</span></summary><p className="mt-3 pr-6 text-[14px] leading-[1.55] text-[#66717e]">{faq.answer}</p></details>)}</div></ProfileCard><ProfileCard icon={<ProfileIcon kind="support"/>} title="Contact your branch"><p className="text-[16px] leading-[1.55] text-[#66717e]">Questions about a specific payment, a rejected proof, or your branch affiliation are handled by your branch. Your branch secretariat holds those records.</p><p className="mt-4 break-all font-semibold text-[#0d5b38]">✉ {previewIdentity.email.replace("practitioner@", "support@")}</p><p className="mt-1 text-xs text-[#66717e]">Example contact only; branch support details are not configured.</p></ProfileCard><ProfileCard icon={<ProfileIcon kind="info"/>} title="About"><p className="text-[16px] leading-[1.55] text-[#66717e]">NBA Legal Fees. An initiative of the NBA Anaocha Branch.</p><p className="mt-4 text-[14px] leading-[1.6] text-[#66717e]">Fees are calculated under the Legal Practitioners (Remuneration for Business, Legal Services and Representation) Order, 2023, made under section 15(3) of the Legal Practitioners Act. That Order is an instrument of the Legal Practitioners Remuneration Committee, not of the Nigerian Bar Association.</p></ProfileCard></div></ProfileFrame>;
}
