import type { CSSProperties } from "react";

export const designTokens = {
  color: {
    primary: "#004D27",
    primaryContainer: "#006837",
    primaryStrong: "#003D20",
    primaryTint: "#9EF6B6",
    primaryDim: "#83D89C",
    onPrimary: "#FFFFFF",
    secondary: "#735C00",
    secondaryContainer: "#EFD051",
    secondaryTint: "#FFE08B",
    goldDim: "#E9C349",
    surface: "#FFFFFF",
    surfaceContainer: "#F6F9F8",
    surfaceMuted: "#EEF4F1",
    inverseSurface: "#23302D",
    ink: "#17211E",
    inkMuted: "#5E6A66",
    inkSubtle: "#7C8783",
    border: "#DCE6E2",
    borderStrong: "#C8D6D0",
    success: "#087A43",
    successContainer: "#CCF8DA",
    warning: "#8A6500",
    warningContainer: "#FFF0B5",
    destructive: "#B91C1C",
    destructiveContainer: "#FDEAEA",
    focus: "#1D8C57",
  },
  spacing: {
    micro: "4px",
    xs: "8px",
    sm: "12px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    xxl: "48px",
  },
  typography: {
    display: { size: "32px", lineHeight: "40px", weight: 700 },
    heading1: { size: "24px", lineHeight: "32px", weight: 700 },
    heading2: { size: "20px", lineHeight: "28px", weight: 650 },
    heading3: { size: "18px", lineHeight: "28px", weight: 600 },
    body: { size: "16px", lineHeight: "24px", weight: 400 },
    label: { size: "12px", lineHeight: "16px", weight: 600 },
  },
  radius: {
    small: "4px",
    medium: "8px",
    large: "12px",
    pill: "999px",
  },
  elevation: {
    sm: "0 1px 2px rgba(0, 50, 26, 0.06), 0 4px 12px rgba(0, 50, 26, 0.04)",
    md: "0 8px 24px rgba(0, 50, 26, 0.10)",
    lg: "0 18px 48px rgba(0, 50, 26, 0.16)",
  },
} as const;

const cssVariableEntries = {
  "--color-primary": designTokens.color.primary,
  "--color-primary-container": designTokens.color.primaryContainer,
  "--color-primary-strong": designTokens.color.primaryStrong,
  "--color-primary-tint": designTokens.color.primaryTint,
  "--color-primary-dim": designTokens.color.primaryDim,
  "--color-on-primary": designTokens.color.onPrimary,
  "--color-secondary": designTokens.color.secondary,
  "--color-secondary-container": designTokens.color.secondaryContainer,
  "--color-secondary-tint": designTokens.color.secondaryTint,
  "--color-gold-dim": designTokens.color.goldDim,
  "--color-surface": designTokens.color.surface,
  "--color-surface-container": designTokens.color.surfaceContainer,
  "--color-surface-muted": designTokens.color.surfaceMuted,
  "--color-inverse-surface": designTokens.color.inverseSurface,
  "--color-ink": designTokens.color.ink,
  "--color-ink-muted": designTokens.color.inkMuted,
  "--color-ink-subtle": designTokens.color.inkSubtle,
  "--color-border": designTokens.color.border,
  "--color-border-strong": designTokens.color.borderStrong,
  "--color-success": designTokens.color.success,
  "--color-success-container": designTokens.color.successContainer,
  "--color-warning": designTokens.color.warning,
  "--color-warning-container": designTokens.color.warningContainer,
  "--color-destructive": designTokens.color.destructive,
  "--color-destructive-container": designTokens.color.destructiveContainer,
  "--color-focus": designTokens.color.focus,
  "--space-micro": designTokens.spacing.micro,
  "--space-xs": designTokens.spacing.xs,
  "--space-sm": designTokens.spacing.sm,
  "--space-md": designTokens.spacing.md,
  "--space-lg": designTokens.spacing.lg,
  "--space-xl": designTokens.spacing.xl,
  "--space-xxl": designTokens.spacing.xxl,
  "--radius-small": designTokens.radius.small,
  "--radius-medium": designTokens.radius.medium,
  "--radius-large": designTokens.radius.large,
  "--radius-pill": designTokens.radius.pill,
  "--shadow-sm": designTokens.elevation.sm,
  "--shadow-md": designTokens.elevation.md,
  "--shadow-lg": designTokens.elevation.lg,
} as const;

export const designTokenCssVariables = cssVariableEntries as CSSProperties;

export type ColorTokenName = keyof typeof designTokens.color;

export const colorTokenDescriptions: Record<ColorTokenName, string> = {
  primary: "NBA Forest · 9.4:1 contrast",
  primaryContainer: "Authority green · 7.6:1",
  primaryStrong: "Deep institutional green",
  primaryTint: "Positive highlight · 12.5:1 dark",
  primaryDim: "Muted authority · 9.0:1 dark",
  onPrimary: "Text and icons on authority green",
  secondary: "Judicial gold ink · 6.2:1",
  secondaryContainer: "Ceremonial seal",
  secondaryTint: "Gold highlight · 11.8:1 dark",
  goldDim: "Heritage accent · 8.4:1 dark",
  surface: "Base paper",
  surfaceContainer: "Component grey",
  surfaceMuted: "Quiet background",
  inverseSurface: "Dark overlay",
  ink: "Primary legal copy",
  inkMuted: "Supporting copy",
  inkSubtle: "Metadata",
  border: "Default divider",
  borderStrong: "Emphasized divider",
  success: "Verified status",
  successContainer: "Verified surface",
  warning: "Pending status",
  warningContainer: "Pending surface",
  destructive: "Sanctions and errors · 6.0:1",
  destructiveContainer: "Error surface",
  focus: "Keyboard focus ring",
};

export function serializeDesignTokens() {
  return JSON.stringify(designTokens, null, 2);
}

